import { Component, OnInit, AfterViewInit, ChangeDetectorRef } from '@angular/core';
import { IonicModule } from '@ionic/angular';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MenuCategoriasComponent } from '../components/menu-categorias/menu-categorias.component';
import { MenuService, CategoriaMenu } from '../services/menu.service';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-tproducto',
  standalone: true,
  imports: [IonicModule, CommonModule, FormsModule, MenuCategoriasComponent],
  templateUrl: './tproducto.page.html',
  styleUrls: ['./tproducto.page.scss'],
})
export class TproductoPage implements OnInit, AfterViewInit {
  isMenuOpen = false;
  categorias$!: Observable<CategoriaMenu[]>;

  productos: any[] = [
    { titulo: 'Switch con luz 12V 35A (verde)', codigo: 'SIWL03', precio: 3.98, imagen: 'assets/switchluzV.jpeg', categoria: 'tapas' },
    { titulo: 'Claxon tono alto tipo disco 12V SEGER', codigo: 'CLXP-0001', precio: 27.5, imagen: 'assets/claxonseger.jpeg' },
    { titulo: 'Medidor de aire metálico hasta 120 PSI', codigo: 'MDAI-01', precio: 14.45, imagen: 'assets/medidoraire.jpeg' },
    { titulo: 'Tapa de gasolina cromada 35mm', codigo: 'TGC.01', precio: 20.5, imagen: 'assets/tapacromada.jpeg' },
    { titulo: 'Soquete de lágrima para foco – 158', codigo: 'SKL2C', precio: 1.2, imagen: 'assets/soquetefoco.jpeg' },
    { titulo: 'Filtro gasolina Toyota (Corona, Corolla)', codigo: 'FGU05', precio: 15.55, imagen: 'assets/filtrogasolina-corolla.jpeg' },
    { titulo: 'Switch palanca ON/OFF 6P', codigo: 'SW-I6P', precio: 4.35, imagen: 'assets/switchpalanca.jpeg' },
    { titulo: 'Switch/trompo de aceite Nissan (FEW Japonés)', codigo: 'SAFEW01', precio: 12.9, imagen: 'assets/switchtrompo-nissan.jpeg' },
    { titulo: 'Switch con luz OFF 12V 3 pines 4 clips rojo', codigo: 'SIWL06', precio: 0.75, imagen: 'assets/switchluzR.jpeg' },
    { titulo: 'Chanchito arrancador 12V', codigo: 'SRL13', precio: 22.8, imagen: 'assets/chanchitoarrancador.jpeg' },
    { titulo: 'Relay electrónico', codigo: 'RE15', precio: 22.7, imagen: 'assets/relayelectronico.jpeg' },
    { titulo: 'Switch levanta luna tipo flecha', codigo: 'SLL01', precio: 6.5, imagen: 'assets/switchlevantaluna.jpeg' },
    { titulo: 'Tapa de gasolina con rosca sin llave', codigo: 'TGC-03', precio: 9.3, imagen: 'assets/tapagasolinaR-sinllave.jpeg', categoria: 'tapas'},
    { titulo: 'Encendedor universal 12V completo', codigo: 'EDC04', precio: 9.9, imagen: 'assets/encendedoruniversal.jpeg' },
    { titulo: 'Sirena retroceso 12V “bebé”', codigo: 'SRNR12V01', precio: 14.7, imagen: 'assets/sirenaretroceso-BB.jpeg' },
    { titulo: 'Porta fusible de uña rojo y negro (x10 und)', codigo: 'PFUÑA01', precio: 2.15, imagen: 'assets/portafusibleRyN.png' },
    { titulo: 'Switch con luz 12V 35A (amarillo)', codigo: 'SIWL01', precio: 3.98, imagen: 'assets/switchluzA.jpeg' },
    { titulo: 'Tapa de gasolina con rosca y llave', codigo: 'TGC-02', precio: 11.8, imagen: 'assets/tapagasolinaR-conllave.jpeg', categoria: 'tapas'},
    { titulo: 'Medidor de aire 120 PSI diagonal', codigo: 'MDA4I', precio: 26.9, imagen: 'assets/medidoraireD.png' },
    { titulo: 'Filtro metal Nissan', codigo: 'FUG04', precio: 7.56, imagen: 'assets/filtrometal-Nissan.jpeg' },
    { titulo: 'Tenaza mediana POS/NEG', codigo: 'TN2', precio: 2.91, imagen: 'assets/tenazamedianaPOS-NEG.jpeg' },
    { titulo: 'Socket de faro H4 (Taiwán)', codigo: 'SKF H4', precio: 3.69, imagen: 'assets/socketfaro-T.jpeg' },
    { titulo: 'Relay tablero 5P 24V con doble resistencia', codigo: 'RDT5P24', precio: 5.2, imagen: 'assets/relaytablero2R.jpeg' },
    { titulo: 'Conectores hembra/macho 4P (par)', codigo: 'CM-H4PCN', precio: 3.2, imagen: 'assets/conectorHM.jpeg' },
    { titulo: 'Conectores hembra/macho 6P (par)', codigo: 'CM-H 6PCN', precio: 4.8, imagen: 'assets/conectorHM-6p.jpeg' },
    { titulo: 'Relay tablero 5P 12V con doble resistencia', codigo: 'RDT5P12', precio: 5.2, imagen: 'assets/relaytablero5P-2R.jpeg' },
    { titulo: 'Claxon de platillo 12V SAFARI', codigo: 'CLXP-12V', precio: 15.25, imagen: 'assets/claxonplatillo-S.jpeg' },
    { titulo: 'Switch con luz 12V 35A (rojo)', codigo: 'SIWL02', precio: 3.98, imagen: 'assets/switchluzA-35A.jpeg' },
    { titulo: 'Chapa de encendido 12V S/M', codigo: 'YW1103-M', precio: 12.5, imagen: 'assets/chapaencendidoS-M.jpeg' },
    { titulo: 'Switch con luz 12V 35A (azul)', codigo: 'SIWL04', precio: 3.98, imagen: 'assets/switchluzAzul-35A.jpeg' },
    { titulo: 'Medidor de aire 50 PSI lateral metálico', codigo: 'MDAI-03', precio: 20.8, imagen: 'assets/medidoraire50PSI.jpeg' },
    { titulo: 'Switch/trompo de aceite universal (FEW Japonés)', codigo: 'SAFEW02', precio: 13.7, imagen: 'assets/switch-trompoaceiteU.jpeg' },
    { titulo: 'Tenaza chica POST/NEG', codigo: 'TN1', precio: 1.6, imagen: 'assets/tenazachica.jpeg' },
    { titulo: 'Soquete relay electrónico sin nombre', codigo: 'SKE SN', precio: 2.3, imagen: 'assets/soqueterelay.jpeg' },
    { titulo: 'Switch palanca ON/OFF 2P', codigo: 'SW-12P', precio: 3.5, imagen: 'assets/switchpalanca2P.jpeg' },
    { titulo: 'Claxon de platillo 24V', codigo: 'CLXP-24V', precio: 16.3, imagen: 'assets/claxonplatillo24V.jpeg' },
    { titulo: 'Back-up alarm 12V/24V', codigo: 'CLXRM-0003', precio: 34, imagen: 'assets/back-upAlarm.jpeg' },
    { titulo: 'Medidor de aire metálico hasta 50 PSI', codigo: 'MDAI-02', precio: 11, imagen: 'assets/medidoraireH50PSI.jpeg' },
    { titulo: 'Tenaza grande', codigo: 'TN3', precio: 4.55, imagen: 'assets/tenazagrande.jpeg' },
    { titulo: 'Conectores hembra/macho 3P (par)', codigo: 'CM-H 3 PCN', precio: 2.7, imagen: 'assets/conectoresH-M3P.jpeg' },
    { titulo: 'Filtro universal gasolina', codigo: 'FGU02', precio: 3.5, imagen: 'assets/filtrogasolinaU.jpeg' },
    { titulo: 'Switch palanca ON/OFF 3P', codigo: 'SW-12P', precio: 3.6, imagen: 'assets/switchpalanca3P.jpeg' },
    { titulo: 'Chapa de encendido universal 12V (metal)', codigo: 'YW1102-M', precio: 21.5, imagen: 'assets/chapaencendidoU.jpeg' },
    { titulo: 'Socket de relay cerámico', codigo: 'SKRCCN', precio: 2.75, imagen: 'assets/socketrelay.png' },
    { titulo: 'Resistencia de bobina', codigo: 'RDB09', precio: 6.95, imagen: 'assets/resistenciaBobina.jpeg' },
    { titulo: 'Chapa de encendido universal 24V (metal)', codigo: 'YW1102-M', precio: 21.95, imagen: 'assets/chapaencendidoU24V.jpeg' },
    { titulo: 'Sirena retroceso 24V “bebé”', codigo: 'SRNR24V02', precio: 14.7, imagen: 'assets/sirenaretroceso24V-BB.jpeg' },
    { titulo: 'Flasher para Tico 12V 3 pin', codigo: 'FSH 3PIN', precio: 9.3, imagen: 'assets/flasher-Tico.jpeg' },
    { titulo: 'Switch palanca ON/OFF 6P', codigo: 'SW-I6P', precio: 4.35, imagen: 'assets/switchpalanca6P.jpeg' },
    { titulo: 'Conectores hembra/macho 2P (par)', codigo: 'CM-H 2PCN', precio: 2.2, imagen: 'assets/conectoresH-M2P.jpeg' }
    // ... aquí pegarias todos los demás productos con "titulo"

    ,{ titulo: 'BORNE PARA TICO', codigo: 'BT-0118', precio: 2.18, imagen: 'assets/BORNE PARA TICO.jpeg' },
{ titulo: 'BORNE TIPO BOSH ESPECIAL', codigo: 'BB-0103', precio: 2.46, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'BORNE TIPO MARIPOSA', codigo: 'BM-0110', precio: 3.67, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'BORNE TIPO MARIPOSA CON TUERCA', codigo: 'BT-0112', precio: 3.40, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'BORNE PARA VOLVO', codigo: 'BV-0123', precio: 3.67, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'BORNE DE PLOMO', codigo: 'BP-0125', precio: 3.80, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'BORNES INDUSTRIAL ( set 2 ) long 7 cm', codigo: 'BO1-007', precio: 24.49, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'CLAXON TIPO DISCO SEGER 12V ALTO TONO', codigo: 'CLXP-0001', precio: 27.50, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'CLAXON DE PLATILLO 12V SAFARI', codigo: 'CLXP-12V', precio: 15.25, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'CLAXON DE PLATILLO 24V', codigo: 'CLXP-24V', precio: 16.30, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SIRENA RETROCESO 12V “BEBE”', codigo: 'SRNR12V01', precio: 14.70, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SIRENA RETROCESO 24V “BEBE”', codigo: 'SRNR24V02', precio: 14.70, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'BACK-UP ALARM 12/24V', codigo: 'CLXRM-0003', precio: 34.00, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY TABLERO 5P 12V CON DOBLE RESISTENCIA', codigo: 'RDT5P12', precio: 5.20, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY TABLERO 5P 24V CON DOBLE RESISTENCIA', codigo: 'RDT5P24', precio: 5.20, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY ELECTRONICO', codigo: 'RE15', precio: 22.70, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SOQUETE RELAY ELECTRONICO', codigo: 'SKE SN', precio: 2.30, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SOQUETE DE FARO H4 (TAIWAN)', codigo: 'SKF H4', precio: 3.69, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SOQUETE DE LAGRIMA PARA FOCO – 158', codigo: 'SKL2C', precio: 1.20, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SOCKET DE RELAY CERAMICO', codigo: 'SKRCCN', precio: 2.75, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH CON LUZ 12V 35A (AMARILLO)', codigo: 'SIWL01', precio: 3.98, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH CON LUZ 12V 35A (ROJO)', codigo: 'SIWL02', precio: 3.98, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH CON LUZ 12V 35A (VERDE)', codigo: 'SIWL03', precio: 3.98, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH CON LUZ 12V 35A (AZUL)', codigo: 'SIWL04', precio: 3.98, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH CON LUZ OFF 12V 3 PINES 4 CLIPS ROJO', codigo: 'SIWL06', precio: 0.75, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PALANCA ON/OFF 2P', codigo: 'SW-12P', precio: 3.50, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PALANCA ON/OFF 3P', codigo: 'SW-12P', precio: 3.60, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PALANCA ON/OFF 6P', codigo: 'SW-I6P', precio: 4.35, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH/TROMPO DE ACEITE NISSAN (FEW JAPONES)', codigo: 'SAFEW01', precio: 12.90, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH/TROMPO DE ACEITE UNIVERSAL (FEW JAPONES)', codigo: 'SAFEW02', precio: 13.70, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH LEVANTA LUNA TIPO FLECHA', codigo: 'SLL01', precio: 6.50, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'CHANCHITO ARRANCADOR 12V', codigo: 'SRL13', precio: 22.80, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'PORTA FUSIBLE DE UÑA ROJO Y NEGRO (x10 UND)', codigo: 'PFUÑA01', precio: 2.15, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'ENCENDEDOR UNIVERSAL 12V COMPLETO', codigo: 'EDC04', precio: 9.90, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'MEDIDOR DE AIRE METALICO HASTA 120 PSI', codigo: 'MDAI-01', precio: 14.45, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'MEDIDOR DE AIRE 120 PSI DIAGONAL', codigo: 'MDA4I', precio: 26.90, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'MEDIDOR DE AIRE METALICO HASTA 50 PSI', codigo: 'MDAI-02', precio: 11.00, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'MEDIDOR DE AIRE 50 PSI LATERAL METALICO', codigo: 'MDAI-03', precio: 20.80, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'TENAZA CHICA POST/NEG', codigo: 'TN1', precio: 1.60, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'TENAZA MEDIANA POS/NEG', codigo: 'TN2', precio: 2.91, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'TENAZA GRANDE', codigo: 'TN3', precio: 4.55, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'FILTRO GASOLINA TOYOTA (CORONA, COROLLA)', codigo: 'FGU05', precio: 15.55, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'FILTRO UNIVERSAL GASOLINA', codigo: 'FGU02', precio: 3.50, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'FILTRO METAL NISSAN', codigo: 'FUG04', precio: 7.56, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'CHAPA DE ENCENDIDO 12V S/M', codigo: 'YW1103-M', precio: 12.50, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'FLASHER PARA TICO 12V 3 PIN', codigo: 'FSH 3PIN', precio: 9.30, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'CONECTORES HEMBRA/MACHO 2P (PAR)', codigo: 'CM-H 2PCN', precio: 2.20, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'CONECTORES HEMBRA/MACHO 3P (PAR)', codigo: 'CM-H 3 PCN', precio: 2.70, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'CONECTORES HEMBRA/MACHO 4P (PAR)', codigo: 'CM-H4PCN', precio: 3.20, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'CONECTORES HEMBRA/MACHO 6P (PAR)', codigo: 'CM-H 6PCN', precio: 4.80, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RESISTENCIA DE BOBINA', codigo: 'RDB09', precio: 6.95, imagen: 'assets/switchluzV.jpeg' },
// bloque 2 
{ titulo: 'INTERRUPTOR LUZ DE FRENO UNIVERSAL', codigo: 'SIFRU-004', precio: 3.95, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'INTERRUPTOR LUZ DE FRENO TICO', codigo: 'SIFTI-005', precio: 4.20, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PRESION ACEITE UNIVERSAL', codigo: 'SWPAU-01', precio: 5.30, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PRESION ACEITE NISSAN', codigo: 'SWPAN-02', precio: 6.10, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PRESION ACEITE TOYOTA', codigo: 'SWPAT-03', precio: 6.75, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PRESION ACEITE DAEWOO', codigo: 'SWPAD-04', precio: 5.65, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PRESION ACEITE MAZDA', codigo: 'SWPAM-05', precio: 6.30, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PRESION ACEITE HYUNDAI', codigo: 'SWPAH-06', precio: 5.95, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PRESION ACEITE KIA', codigo: 'SWPAK-07', precio: 5.95, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PRESION ACEITE MITSUBISHI', codigo: 'SWPAMI-08', precio: 6.55, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PRESION ACEITE SUZUKI', codigo: 'SWPASU-09', precio: 6.10, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PRESION ACEITE VOLVO', codigo: 'SWPAV-10', precio: 7.50, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PRESION ACEITE CHEVROLET', codigo: 'SWPACH-11', precio: 6.20, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PRESION ACEITE VOLKSWAGEN', codigo: 'SWPAVW-12', precio: 6.95, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PRESION ACEITE FORD', codigo: 'SWPAF-13', precio: 6.35, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PRESION ACEITE HONDA', codigo: 'SWPAHO-14', precio: 6.45, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PRESION ACEITE MERCEDES', codigo: 'SWPAME-15', precio: 7.80, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PRESION ACEITE RENAULT', codigo: 'SWPAR-16', precio: 6.60, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PRESION ACEITE PEUGEOT', codigo: 'SWPAPE-17', precio: 6.90, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PRESION ACEITE NISSAN PICKUP', codigo: 'SWPANP-18', precio: 6.85, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PALANCA UNIVERSAL METALICO', codigo: 'SWPMU-19', precio: 4.10, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PALANCA UNIVERSAL PLASTICO', codigo: 'SWPUP-20', precio: 3.80, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PALANCA ALTA RESISTENCIA', codigo: 'SWPAR-21', precio: 5.95, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PALANCA PESADO 6P', codigo: 'SWPP6-22', precio: 6.75, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PALANCA METALICO CORTO', codigo: 'SWPMC-23', precio: 3.45, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH PALANCA METALICO LARGO', codigo: 'SWPML-24', precio: 4.10, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH LUCES FRENO TIPO ROSCA UNIVERSAL', codigo: 'SWLU-25', precio: 3.85, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH LUCES FRENO TICO', codigo: 'SWLT-26', precio: 4.15, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH LUCES FRENO HYUNDAI', codigo: 'SWLH-27', precio: 4.35, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH LUCES FRENO KIA', codigo: 'SWLK-28', precio: 4.35, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH LUCES FRENO CHEVROLET', codigo: 'SWLCH-29', precio: 4.55, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH LUCES FRENO VOLKSWAGEN', codigo: 'SWLVW-30', precio: 4.75, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH LUCES FRENO FORD', codigo: 'SWLF-31', precio: 4.45, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH LUCES FRENO HONDA', codigo: 'SWLHO-32', precio: 4.60, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH LUCES FRENO MAZDA', codigo: 'SWLM-33', precio: 4.40, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH LUCES FRENO SUZUKI', codigo: 'SWLSU-34', precio: 4.50, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH LUCES FRENO MITSUBISHI', codigo: 'SWLMI-35', precio: 4.50, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH LUCES FRENO NISSAN', codigo: 'SWLN-36', precio: 4.60, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH LUCES FRENO TOYOTA', codigo: 'SWLTY-37', precio: 4.65, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH LUCES FRENO DAEWOO', codigo: 'SWLD-38', precio: 4.45, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH LUCES FRENO PEUGEOT', codigo: 'SWLPE-39', precio: 4.75, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH LUCES FRENO RENAULT', codigo: 'SWLR-40', precio: 4.85, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH LUCES FRENO VOLVO', codigo: 'SWLV-41', precio: 5.05, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH ENCENDIDO UNIVERSAL', codigo: 'SWENU-42', precio: 8.25, imagen: 'assets/SWITCH ENCENDIDO UNIVERSAL.jpeg' },
{ titulo: 'SWITCH ENCENDIDO NISSAN', codigo: 'SWENN-43', precio: 9.10, imagen: 'assets/SWITCH ENCENDIDO nissan.jpg' },
{ titulo: 'SWITCH ENCENDIDO TOYOTA', codigo: 'SWENT-44', precio: 9.30, imagen: 'assets/switch encendido toyota.jpg' },
{ titulo: 'SWITCH ENCENDIDO HYUNDAI', codigo: 'SWENH-45', precio: 8.95, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH ENCENDIDO KIA', codigo: 'SWENK-46', precio: 8.85, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH ENCENDIDO CHEVROLET', codigo: 'SWENCH-47', precio: 9.50, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH ENCENDIDO VOLKSWAGEN', codigo: 'SWENVW-48', precio: 9.75, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH ENCENDIDO FORD', codigo: 'SWENF-49', precio: 9.20, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH ENCENDIDO HONDA', codigo: 'SWENHO-50', precio: 9.10, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH ENCENDIDO MAZDA', codigo: 'SWENM-51', precio: 9.15, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH ENCENDIDO SUZUKI', codigo: 'SWENSU-52', precio: 9.20, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH ENCENDIDO MITSUBISHI', codigo: 'SWENMI-53', precio: 9.30, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH ENCENDIDO RENAULT', codigo: 'SWENR-54', precio: 9.65, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH ENCENDIDO PEUGEOT', codigo: 'SWENPE-55', precio: 9.70, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH ENCENDIDO VOLVO', codigo: 'SWENV-56', precio: 9.85, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'SWITCH ENCENDIDO DAEWOO', codigo: 'SWEND-57', precio: 9.00, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY LUCES UNIVERSAL', codigo: 'RLU-58', precio: 4.95, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY LUCES TICO', codigo: 'RLT-59', precio: 5.10, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY LUCES HYUNDAI', codigo: 'RLH-60', precio: 5.05, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY LUCES KIA', codigo: 'RLK-61', precio: 5.10, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY LUCES CHEVROLET', codigo: 'RLCH-62', precio: 5.20, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY LUCES VOLKSWAGEN', codigo: 'RLVW-63', precio: 5.25, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY LUCES FORD', codigo: 'RLF-64', precio: 5.15, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY LUCES HONDA', codigo: 'RLHO-65', precio: 5.25, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY LUCES MAZDA', codigo: 'RLM-66', precio: 5.05, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY LUCES SUZUKI', codigo: 'RLSU-67', precio: 5.10, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY LUCES MITSUBISHI', codigo: 'RLMI-68', precio: 5.20, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY LUCES RENAULT', codigo: 'RLR-69', precio: 5.40, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY LUCES PEUGEOT', codigo: 'RLPE-70', precio: 5.35, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY LUCES VOLVO', codigo: 'RLV-71', precio: 5.55, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY LUCES DAEWOO', codigo: 'RLD-72', precio: 5.10, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'FLASHER UNIVERSAL 3 PINES', codigo: 'FSHU-73', precio: 3.60, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'FLASHER TICO 3 PINES', codigo: 'FSHT-74', precio: 3.75, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'FLASHER HYUNDAI 3 PINES', codigo: 'FSHH-75', precio: 3.70, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'FLASHER KIA 3 PINES', codigo: 'FSHK-76', precio: 3.70, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'FLASHER CHEVROLET 3 PINES', codigo: 'FSHCH-77', precio: 3.80, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'FLASHER VOLKSWAGEN 3 PINES', codigo: 'FSHVW-78', precio: 3.85, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'FLASHER FORD 3 PINES', codigo: 'FSHF-79', precio: 3.75, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'FLASHER HONDA 3 PINES', codigo: 'FSHHO-80', precio: 3.80, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'FLASHER MAZDA 3 PINES', codigo: 'FSHM-81', precio: 3.70, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'FLASHER SUZUKI 3 PINES', codigo: 'FSHSU-82', precio: 3.75, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'FLASHER MITSUBISHI 3 PINES', codigo: 'FSHMI-83', precio: 3.85, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'FLASHER RENAULT 3 PINES', codigo: 'FSHR-84', precio: 3.95, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'FLASHER PEUGEOT 3 PINES', codigo: 'FSHPE-85', precio: 3.85, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'FLASHER VOLVO 3 PINES', codigo: 'FSHV-86', precio: 4.15, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'FLASHER DAEWOO 3 PINES', codigo: 'FSHD-87', precio: 3.75, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY ARRANQUE UNIVERSAL', codigo: 'RAU-88', precio: 6.45, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY ARRANQUE NISSAN', codigo: 'RAN-89', precio: 7.20, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY ARRANQUE TOYOTA', codigo: 'RAT-90', precio: 7.50, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY ARRANQUE HYUNDAI', codigo: 'RAH-91', precio: 7.10, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY ARRANQUE KIA', codigo: 'RAK-92', precio: 7.05, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY ARRANQUE CHEVROLET', codigo: 'RACH-93', precio: 7.60, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY ARRANQUE VOLKSWAGEN', codigo: 'RAVW-94', precio: 7.85, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY ARRANQUE FORD', codigo: 'RAF-95', precio: 7.25, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY ARRANQUE HONDA', codigo: 'RAHO-96', precio: 7.15, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY ARRANQUE MAZDA', codigo: 'RAM-97', precio: 7.20, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY ARRANQUE SUZUKI', codigo: 'RASU-98', precio: 7.15, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY ARRANQUE MITSUBISHI', codigo: 'RAMI-99', precio: 7.35, imagen: 'assets/switchluzV.jpeg' },
{ titulo: 'RELAY ARRANQUE RENAULT', codigo: 'RAR-100', precio: 7.60, imagen: 'assets/switchluzV.jpeg' },
// 3
{ titulo: 'SIRENA UNIVERSAL 12V TIPO CAMIÓN', codigo: 'SRNCM-101', precio: 12.50, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SIRENA RETROCESO TIPO “BEBÉ” 12V', codigo: 'SRNBEBE12-102', precio: 14.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SIRENA RETROCESO TIPO “BEBÉ” 24V', codigo: 'SRNBEBE24-103', precio: 15.30, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SIRENA UNIVERSAL DOBLE TONO 12V', codigo: 'SRNDT12-104', precio: 16.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SIRENA UNIVERSAL DOBLE TONO 24V', codigo: 'SRNDT24-105', precio: 17.40, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SIRENA CORTA FUEGO TIPO CAMIÓN 12V', codigo: 'SRCF12-106', precio: 18.95, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SIRENA CORTA FUEGO TIPO CAMIÓN 24V', codigo: 'SRCF24-107', precio: 19.50, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'FLASHER CAMIÓN 24V UNIVERSAL', codigo: 'FSHCM24-108', precio: 5.50, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'FLASHER CAMIÓN 24V 3P', codigo: 'FSH3P24-109', precio: 5.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'FLASHER UNIVERSAL 12V 2 PINES', codigo: 'FSHU12-110', precio: 3.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'FLASHER UNIVERSAL 12V 3 PINES', codigo: 'FSHU12-111', precio: 4.00, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'FLASHER UNIVERSAL 12V 4 PINES', codigo: 'FSHU12-112', precio: 4.30, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'FLASHER CAMIÓN 24V 2 PINES', codigo: 'FSHCM24-113', precio: 5.70, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'FLASHER CAMIÓN 24V 4 PINES', codigo: 'FSHCM24-114', precio: 6.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'FLASHER LED UNIVERSAL 12V/24V', codigo: 'FSHLED-115', precio: 7.25, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SOQUETE UNIVERSAL H4 CERÁMICO', codigo: 'SCKTH4-116', precio: 2.85, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SOQUETE UNIVERSAL H7 CERÁMICO', codigo: 'SCKTH7-117', precio: 2.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SOQUETE UNIVERSAL H1 CERÁMICO', codigo: 'SCKTH1-118', precio: 2.75, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SOQUETE UNIVERSAL H3 CERÁMICO', codigo: 'SCKTH3-119', precio: 2.75, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SOQUETE UNIVERSAL H11 CERÁMICO', codigo: 'SCKTH11-120', precio: 2.95, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SOQUETE UNIVERSAL HB3 CERÁMICO', codigo: 'SCKTHB3-121', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SOQUETE UNIVERSAL HB4 CERÁMICO', codigo: 'SCKTHB4-122', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SOQUETE UNIVERSAL P21W', codigo: 'SCKTP21W-123', precio: 2.40, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SOQUETE UNIVERSAL T20', codigo: 'SCKTT20-124', precio: 2.45, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SOQUETE UNIVERSAL W5W', codigo: 'SCKTW5W-125', precio: 2.35, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SOQUETE UNIVERSAL BA15S', codigo: 'SCKTBA15S-126', precio: 2.60, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SOQUETE UNIVERSAL BAY15D', codigo: 'SCKTBAY15D-127', precio: 2.60, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SOQUETE UNIVERSAL BAU15S', codigo: 'SCKTBAU15S-128', precio: 2.60, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SOQUETE UNIVERSAL T10', codigo: 'SCKTT10-129', precio: 2.30, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SOQUETE UNIVERSAL FESTOON 31mm', codigo: 'SCKTF31-130', precio: 2.25, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SOQUETE UNIVERSAL FESTOON 36mm', codigo: 'SCKTF36-131', precio: 2.30, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SOQUETE UNIVERSAL FESTOON 39mm', codigo: 'SCKTF39-132', precio: 2.35, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'SOQUETE UNIVERSAL FESTOON 41mm', codigo: 'SCKTF41-133', precio: 2.40, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CLAXON DE PLATILLO 12V TIPO S', codigo: 'CLXPL12S-134', precio: 13.50, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CLAXON DE PLATILLO 24V TIPO S', codigo: 'CLXPL24S-135', precio: 14.50, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CLAXON TIPO DISCO UNIVERSAL 12V', codigo: 'CLXDS12U-136', precio: 12.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CLAXON TIPO DISCO UNIVERSAL 24V', codigo: 'CLXDS24U-137', precio: 13.40, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CLAXON DE CAMIÓN DOBLE TONO', codigo: 'CLXCMDBL-138', precio: 18.50, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CLAXON DE CAMIÓN LARGO TONO', codigo: 'CLXCM-LT-139', precio: 20.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'ENCENDEDOR UNIVERSAL COMPLETO', codigo: 'ENCUNI-140', precio: 9.50, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'ENCENDEDOR DE REPUESTO UNIVERSAL', codigo: 'ENCREPU-141', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CHAPA DE ENCENDIDO UNIVERSAL C/ LLAVE', codigo: 'CHENCU-142', precio: 10.75, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CHAPA DE ENCENDIDO UNIVERSAL METAL', codigo: 'CHENUM-143', precio: 12.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CHAPA DE ENCENDIDO UNIVERSAL 24V', codigo: 'CHENU24-144', precio: 14.50, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'RELAY UNIVERSAL 4 PINES 12V', codigo: 'RELU412-145', precio: 4.50, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'RELAY UNIVERSAL 5 PINES 12V', codigo: 'RELU512-146', precio: 4.60, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'RELAY UNIVERSAL 5 PINES 24V', codigo: 'RELU524-147', precio: 4.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'RELAY CON BASE UNIVERSAL 12V', codigo: 'RELUB12-148', precio: 6.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'RELAY CON BASE UNIVERSAL 24V', codigo: 'RELUB24-149', precio: 6.50, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE UNIVERSAL PARA FUSIBLE PLANO', codigo: 'PFUPL-150', precio: 2.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE UNIVERSAL PARA FUSIBLE TIPO UÑA', codigo: 'PFUÑA-151', precio: 2.25, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE UNIVERSAL TIPO MINI', codigo: 'PFUMI-152', precio: 2.30, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'FUSIBLE PLANO 10A (x10 und)', codigo: 'FSPL10-153', precio: 1.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'FUSIBLE PLANO 15A (x10 und)', codigo: 'FSPL15-154', precio: 1.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'FUSIBLE PLANO 20A (x10 und)', codigo: 'FSPL20-155', precio: 1.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'FUSIBLE PLANO 25A (x10 und)', codigo: 'FSPL25-156', precio: 1.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'FUSIBLE PLANO 30A (x10 und)', codigo: 'FSPL30-157', precio: 1.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'FUSIBLE PLANO 40A (x10 und)', codigo: 'FSPL40-158', precio: 1.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'FUSIBLE DE VIDRIO 5A (x10 und)', codigo: 'FSVG5-159', precio: 1.50, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'FUSIBLE DE VIDRIO 10A (x10 und)', codigo: 'FSVG10-160', precio: 1.50, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'FUSIBLE DE VIDRIO 15A (x10 und)', codigo: 'FSVG15-161', precio: 1.50, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'FUSIBLE DE VIDRIO 20A (x10 und)', codigo: 'FSVG20-162', precio: 1.50, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'FUSIBLE DE VIDRIO 25A (x10 und)', codigo: 'FSVG25-163', precio: 1.50, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'FUSIBLE DE VIDRIO 30A (x10 und)', codigo: 'FSVG30-164', precio: 1.50, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CONECTOR UNIVERSAL HEMBRA 2P', codigo: 'CNH2P-165', precio: 2.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CONECTOR UNIVERSAL MACHO 2P', codigo: 'CNM2P-166', precio: 2.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CONECTOR UNIVERSAL HEMBRA/MACHO 2P (PAR)', codigo: 'CNHM2P-167', precio: 2.25, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CONECTOR UNIVERSAL HEMBRA/MACHO 3P (PAR)', codigo: 'CNHM3P-168', precio: 2.60, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CONECTOR UNIVERSAL HEMBRA/MACHO 4P (PAR)', codigo: 'CNHM4P-169', precio: 2.95, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CONECTOR UNIVERSAL HEMBRA/MACHO 6P (PAR)', codigo: 'CNHM6P-170', precio: 3.30, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CONECTOR UNIVERSAL HEMBRA/MACHO 8P (PAR)', codigo: 'CNHM8P-171', precio: 3.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CONECTOR UNIVERSAL HEMBRA/MACHO 10P (PAR)', codigo: 'CNHM10P-172', precio: 4.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL TIPO UÑETA 2.8MM (x10 und)', codigo: 'TRU2.8-173', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL TIPO UÑETA 4.8MM (x10 und)', codigo: 'TRU4.8-174', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL TIPO UÑETA 6.3MM (x10 und)', codigo: 'TRU6.3-175', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
// bloque

{ titulo: 'TERMINAL REDONDO PEQUEÑO (x10 und)', codigo: 'TRRP-176', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL REDONDO MEDIANO (x10 und)', codigo: 'TRRM-177', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL REDONDO GRANDE (x10 und)', codigo: 'TRRG-178', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL HORQUILLA PEQUEÑO (x10 und)', codigo: 'TRHP-179', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL HORQUILLA MEDIANO (x10 und)', codigo: 'TRHM-180', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL HORQUILLA GRANDE (x10 und)', codigo: 'TRHG-181', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL ESPIGA PEQUEÑO (x10 und)', codigo: 'TREP-182', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL ESPIGA MEDIANO (x10 und)', codigo: 'TREM-183', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL ESPIGA GRANDE (x10 und)', codigo: 'TREG-184', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL OJO PEQUEÑO (x10 und)', codigo: 'TROJOP-185', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL OJO MEDIANO (x10 und)', codigo: 'TROJOM-186', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL OJO GRANDE (x10 und)', codigo: 'TROJOG-187', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL HEMBRA AISLADO (x10 und)', codigo: 'TRHAI-188', precio: 1.30, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL MACHO AISLADO (x10 und)', codigo: 'TRMAI-189', precio: 1.30, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL UÑA AISLADO (x10 und)', codigo: 'TRUAI-190', precio: 1.30, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL OJO AISLADO PEQUEÑO (x10 und)', codigo: 'TROAI-P-191', precio: 1.30, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL OJO AISLADO MEDIANO (x10 und)', codigo: 'TROAI-M-192', precio: 1.30, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL OJO AISLADO GRANDE (x10 und)', codigo: 'TROAI-G-193', precio: 1.40, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL TIPO ESPIGA AISLADO (x10 und)', codigo: 'TREAI-194', precio: 1.30, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL TIPO HORQUILLA AISLADO (x10 und)', codigo: 'TRHAI-195', precio: 1.30, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTA FUSIBLE DE UÑA UNIVERSAL', codigo: 'PFUUNI-196', precio: 2.15, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTA FUSIBLE PLANO UNIVERSAL', codigo: 'PFPLUNI-197', precio: 2.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTA FUSIBLE MINI UNIVERSAL', codigo: 'PFMINI-198', precio: 2.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTA FUSIBLE TIPO TUBO', codigo: 'PFTUBO-199', precio: 2.40, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTA FUSIBLE TIPO VIDRIO', codigo: 'PFVID-200', precio: 2.40, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CABLE TIPO BOBINA Nº 16', codigo: 'CB16-201', precio: 0.85, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CABLE TIPO BOBINA Nº 14', codigo: 'CB14-202', precio: 1.05, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CABLE TIPO BOBINA Nº 12', codigo: 'CB12-203', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CABLE TIPO BOBINA Nº 10', codigo: 'CB10-204', precio: 1.55, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CABLE TIPO BOBINA Nº 8', codigo: 'CB08-205', precio: 1.95, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CABLE TIPO BOBINA Nº 6', codigo: 'CB06-206', precio: 2.35, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CABLE TIPO BOBINA Nº 4', codigo: 'CB04-207', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CABLE TIPO BOBINA Nº 2', codigo: 'CB02-208', precio: 4.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CABLE TIPO BOBINA Nº 0', codigo: 'CB00-209', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CABLE PARA BATERÍA Nº 8', codigo: 'CBBAT08-210', precio: 2.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CABLE PARA BATERÍA Nº 6', codigo: 'CBBAT06-211', precio: 2.65, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CABLE PARA BATERÍA Nº 4', codigo: 'CBBAT04-212', precio: 3.45, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CABLE PARA BATERÍA Nº 2', codigo: 'CBBAT02-213', precio: 4.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CABLE PARA BATERÍA Nº 0', codigo: 'CBBAT00-214', precio: 6.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CONECTOR RÁPIDO UNIVERSAL AZUL (x10 und)', codigo: 'CRUAZUL-215', precio: 2.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CONECTOR RÁPIDO UNIVERSAL ROJO (x10 und)', codigo: 'CRUROJO-216', precio: 2.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CONECTOR RÁPIDO UNIVERSAL AMARILLO (x10 und)', codigo: 'CRUAMA-217', precio: 2.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CONECTOR RÁPIDO UNIVERSAL NEGRO (x10 und)', codigo: 'CRUNEG-218', precio: 2.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE NEGRA', codigo: 'CTAISN-219', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE ROJA', codigo: 'CTAISR-220', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE AZUL', codigo: 'CTAISA-221', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE VERDE', codigo: 'CTAISV-222', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE AMARILLA', codigo: 'CTAISM-223', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE BLANCA', codigo: 'CTAISB-224', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE GRIS', codigo: 'CTAISG-225', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE CELESTE', codigo: 'CTAISCE-226', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE NARANJA', codigo: 'CTAISNAR-227', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE MARRÓN', codigo: 'CTAISMARR-228', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE ROSADA', codigo: 'CTAISRO-229', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE MORADA', codigo: 'CTAISMO-230', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE LILA', codigo: 'CTAISLI-231', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE BEIGE', codigo: 'CTAISBE-232', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE TURQUESA', codigo: 'CTAISTUR-233', precio: 1.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE ORO', codigo: 'CTAISORO-234', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE PLATA', codigo: 'CTAISPLA-235', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE COBRE', codigo: 'CTAISCOB-236', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE BRONCE', codigo: 'CTAISBRO-237', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE PERLA', codigo: 'CTAISPER-238', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE CHAMPÁN', codigo: 'CTAISCHA-239', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE VIOLETA', codigo: 'CTAISVIO-240', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE LIMÓN', codigo: 'CTAISLIM-241', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE UVA', codigo: 'CTAISUVA-242', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE CHICLE', codigo: 'CTAISCHI-243', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE FRESA', codigo: 'CTAISFRE-244', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE SALMÓN', codigo: 'CTAISSAL-245', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE CORAL', codigo: 'CTAISCOR-246', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE MOSTAZA', codigo: 'CTAISMOS-247', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE MENTA', codigo: 'CTAISMEN-248', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE AGUAMARINA', codigo: 'CTAISAGUA-249', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE PETRÓLEO', codigo: 'CTAISPET-250', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
// bloque 4
{ titulo: 'CINTA AISLANTE AQUA', codigo: 'CTAISACQUA-251', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE SKY', codigo: 'CTAISSKY-252', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE PISTACHO', codigo: 'CTAISPIST-253', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE OLIVA', codigo: 'CTAISOLI-254', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE TERRACOTA', codigo: 'CTAISTERR-255', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE CAFÉ', codigo: 'CTAISCAF-256', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE LADRILLO', codigo: 'CTAISLADR-257', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE MARFIL', codigo: 'CTAISMARF-258', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE JADE', codigo: 'CTAISJADE-259', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE ESCARLATA', codigo: 'CTAISESC-260', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE GRANA', codigo: 'CTAISGRA-261', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE RÚSTICO', codigo: 'CTAISRUS-262', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE HUESO', codigo: 'CTAISHUE-263', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE PERGAMINO', codigo: 'CTAISPERG-264', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE ARENA', codigo: 'CTAISARE-265', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE CORCHO', codigo: 'CTAISCORC-266', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE PLOMO', codigo: 'CTAISPLOM-267', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE PIEDRA', codigo: 'CTAISPIED-268', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE ZAFIRO', codigo: 'CTAISZAF-269', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE RUBÍ', codigo: 'CTAISRUB-270', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE ÓNIX', codigo: 'CTAISONIX-271', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE GRANATE', codigo: 'CTAISGRA2-272', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE ÁMBAR', codigo: 'CTAISAMB-273', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE ESPUMA', codigo: 'CTAISESP-274', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE ESPUMA ROJA', codigo: 'CTAISESPR-275', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE ESPUMA AZUL', codigo: 'CTAISESPA-276', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE ESPUMA VERDE', codigo: 'CTAISESPV-277', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE ESPUMA AMARILLA', codigo: 'CTAISESPAM-278', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE ESPUMA NEGRA', codigo: 'CTAISESPN-279', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE ESPUMA BLANCA', codigo: 'CTAISESPB-280', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE ESPUMA GRIS', codigo: 'CTAISESPG-281', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'CINTA AISLANTE ESPUMA MARRÓN', codigo: 'CTAISESPM-282', precio: 1.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA NEGRO', codigo: 'TBN-283', precio: 2.50, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA ROJO', codigo: 'TBR-284', precio: 2.50, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL', codigo: 'TBU-285', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA PESADO', codigo: 'TBP-286', precio: 3.60, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO FORD', codigo: 'TBFORD-287', precio: 3.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO TOYOTA', codigo: 'TBTOY-288', precio: 3.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO NISSAN', codigo: 'TBNISS-289', precio: 3.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO UNIVERSAL CERRADO', codigo: 'TBUC-290', precio: 4.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO UNIVERSAL ABIERTO', codigo: 'TBUA-291', precio: 4.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO JAPONÉS', codigo: 'TBJAP-292', precio: 4.50, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO EUROPEO', codigo: 'TBEUR-293', precio: 4.50, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA LATÓN', codigo: 'TBLAT-294', precio: 5.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA HEAVY DUTY', codigo: 'TBHD-295', precio: 5.60, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA PESADO JAPONÉS', codigo: 'TBPJAP-296', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO GOLF', codigo: 'TBGOLF-297', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO AUDI', codigo: 'TBAUDI-298', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO BMW', codigo: 'TBBMW-299', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO MERCEDES', codigo: 'TBMERC-300', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO PEUGEOT', codigo: 'TBPEUG-301', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO CITROËN', codigo: 'TBCIT-302', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO RENAULT', codigo: 'TBREN-303', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO FIAT', codigo: 'TBFIAT-304', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO VOLVO', codigo: 'TBVOLV-305', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO HYUNDAI', codigo: 'TBHYUN-306', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO KIA', codigo: 'TBKIA-307', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO MITSUBISHI', codigo: 'TBMIT-308', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO SUZUKI', codigo: 'TBSUZ-309', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO MAZDA', codigo: 'TBMAZ-310', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO SUBARU', codigo: 'TBSUB-311', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO HONDA', codigo: 'TBHON-312', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO TOYOTA II', codigo: 'TBTOY2-313', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO NISSAN II', codigo: 'TBNISS2-314', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA TIPO UNIVERSAL II', codigo: 'TBU2-315', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL PESADO', codigo: 'TBUPES-316', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL LARGO', codigo: 'TBULAR-317', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL CORTO', codigo: 'TBUCORT-318', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL PLOMO', codigo: 'TBU-PLOM-319', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL COBRE', codigo: 'TBU-COB-320', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL BRONCE', codigo: 'TBU-BRO-321', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL LATÓN', codigo: 'TBU-LAT-322', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL HIERRO', codigo: 'TBU-HIER-323', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL ACERO', codigo: 'TBU-ACER-324', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL ALUMINIO', codigo: 'TBU-ALUM-325', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL ZINC', codigo: 'TBU-ZINC-326', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL ESTAÑO', codigo: 'TBU-ESTA-327', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL NÍQUEL', codigo: 'TBU-NIQ-328', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL CROMO', codigo: 'TBU-CRO-329', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL TITANIO', codigo: 'TBU-TIT-330', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL INOX', codigo: 'TBU-INOX-331', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL ORO', codigo: 'TBU-ORO-332', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL PLATA', codigo: 'TBU-PLA-333', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL PINTADO', codigo: 'TBU-PINT-334', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL REFORZADO', codigo: 'TBU-REF-335', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
//bloque 5 
{ titulo: 'TERMINAL BATERÍA UNIVERSAL ALTO', codigo: 'TBU-ALTO-336', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL BAJO', codigo: 'TBU-BAJO-337', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL ESPECIAL', codigo: 'TBU-ESP-338', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL PREMIUM', codigo: 'TBU-PREM-339', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL EXTRAPESADO', codigo: 'TBU-EXTRA-340', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL DOBLE ROSCA', codigo: 'TBU-DOBLE-341', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL CUBIERTO', codigo: 'TBU-CUB-342', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL DESNUDO', codigo: 'TBU-DES-343', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL HEAVY', codigo: 'TBU-HEAVY-344', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'TERMINAL BATERÍA UNIVERSAL LIGHT', codigo: 'TBU-LIGHT-345', precio: 5.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE UNIVERSAL', codigo: 'PFU-346', precio: 1.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE LARGO', codigo: 'PFL-347', precio: 2.00, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE CORTO', codigo: 'PFC-348', precio: 2.00, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE REFORZADO', codigo: 'PFR-349', precio: 2.50, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE ALTO VOLTAJE', codigo: 'PFAV-350', precio: 2.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE PLÁSTICO', codigo: 'PFPL-351', precio: 1.60, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE METAL', codigo: 'PFMET-352', precio: 2.40, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE AGUJA', codigo: 'PFAGUJA-353', precio: 2.70, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE CERÁMICO', codigo: 'PFCER-354', precio: 2.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE MINI', codigo: 'PFMINI-355', precio: 1.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE MAXI', codigo: 'PFMAXI-356', precio: 2.50, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE TIPO JAPÓN', codigo: 'PFJAP-357', precio: 2.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE TIPO USA', codigo: 'PFUSA-358', precio: 2.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE TIPO EUROPA', codigo: 'PFEUR-359', precio: 2.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE TIPO UNIVERSAL', codigo: 'PFUNI-360', precio: 2.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE PLANO', codigo: 'PFPLA-361', precio: 1.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE REDONDO', codigo: 'PFRED-362', precio: 1.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE TIPO TUBO', codigo: 'PFTUB-363', precio: 1.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE TIPO LAMINA', codigo: 'PFLAM-364', precio: 1.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE TIPO CABLE', codigo: 'PFCABL-365', precio: 2.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE TIPO FICHA', codigo: 'PFFICHA-366', precio: 2.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE TIPO CUCHILLA', codigo: 'PFCCU-367', precio: 2.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DOBLE', codigo: 'PFDOBLE-368', precio: 2.20, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE TRIPLE', codigo: 'PFTRIPLE-369', precio: 2.50, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE CUÁDRUPLE', codigo: 'PFQUAD-370', precio: 2.80, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE QUÍNTUPLE', codigo: 'PFQUIN-371', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE SEXTUPLE', codigo: 'PFSEX-372', precio: 3.40, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE SÉPTUPLE', codigo: 'PFSEPT-373', precio: 3.70, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE OCTUPLE', codigo: 'PFOCT-374', precio: 4.00, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE NONUPLE', codigo: 'PFNON-375', precio: 4.30, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DÉCUPLE', codigo: 'PFDEC-376', precio: 4.60, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE PANEL', codigo: 'PFPANEL-377', precio: 2.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE TABLERO', codigo: 'PFTABL-378', precio: 2.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE MOTOR', codigo: 'PFMOT-379', precio: 2.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE BATERÍA', codigo: 'PFBAT-380', precio: 2.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE LUZ', codigo: 'PFLUZ-381', precio: 2.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE SIRENA', codigo: 'PFSIRE-382', precio: 2.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE BOCINA', codigo: 'PFBOC-383', precio: 2.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE RADIO', codigo: 'PFRAD-384', precio: 2.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE TUBO', codigo: 'PFTUBO-385', precio: 2.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE FOCO', codigo: 'PFFOCO-386', precio: 2.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE INTERMITENTE', codigo: 'PFINT-387', precio: 2.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE STOP', codigo: 'PFSTOP-388', precio: 2.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE CARGA', codigo: 'PFCARG-389', precio: 2.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE BOMBILLA', codigo: 'PFBOMB-390', precio: 2.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE EMERGENCIA', codigo: 'PFEMERG-391', precio: 2.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE LINTERNA', codigo: 'PFLINT-392', precio: 2.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE HAZ', codigo: 'PFHAZ-393', precio: 2.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE LÍNEA', codigo: 'PFLINE-394', precio: 2.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE SERVICIO', codigo: 'PFSERV-395', precio: 2.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE TRABAJO', codigo: 'PFTRAB-396', precio: 2.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE SEÑAL', codigo: 'PFSEN-397', precio: 2.90, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE PANEL LED', codigo: 'PFPLED-398', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE CARGADOR', codigo: 'PFCARGA-399', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE USB', codigo: 'PFUSB-400', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE GPS', codigo: 'PFGPS-401', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE CAMARA', codigo: 'PFCAM-402', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE DVR', codigo: 'PFDVR-403', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE SENSOR', codigo: 'PFSENS-404', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE MICRO', codigo: 'PFMIC-405', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE ENCENDEDOR', codigo: 'PFENCEN-406', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE ENTRADA', codigo: 'PFENTRA-407', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE SALIDA', codigo: 'PFSALI-408', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE CABLEADO', codigo: 'PFCABLE-409', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE SEGURIDAD', codigo: 'PFSEGU-410', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE CONTROL', codigo: 'PFCONT-411', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE DOMO', codigo: 'PFDOMO-412', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE PANEL DIGITAL', codigo: 'PFPDIG-413', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE LUZ LED', codigo: 'PFLLED-414', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE FARO', codigo: 'PFFARO-415', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE PLACA', codigo: 'PFPLAC-416', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE PARLANTE', codigo: 'PFPARL-417', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE ALARMA', codigo: 'PFALAR-418', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE CAMION', codigo: 'PFCAMION-419', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE TRAILER', codigo: 'PFTRAIL-420', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE BUS', codigo: 'PFBUS-421', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE MOTO', codigo: 'PFMOTO-422', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' },
{ titulo: 'PORTAFUSIBLE DE AUTO', codigo: 'PFAUTO-423', precio: 3.10, imagen: 'assets/conectoresH-M2P.jpeg' }

  ];

  searchTerm: string = '';
  productosFiltrados: any[] = [];

  constructor(private menuService: MenuService, private cdr: ChangeDetectorRef) {}

  ngOnInit() {
    this.categorias$ = this.menuService.categorias$;

    // 🔥 Aquí hacemos la transformación SOLO si los productos vienen con "titulo"
    if (this.productos.length > 0 && this.productos[0].titulo) {
      this.productos = this.productos.map(p => ({
        nombre: p.titulo,
        descripcion: '', // puedes agregar texto si deseas
        codigo: p.codigo,
        precio: p.precio,
        imagen: p.imagen,
        categoria: p.categoria || ''
      }));
    }

    // Inicializa el listado filtrado
    this.resetFiltrado();
  }
  // Filtra productos por subcategoría de forma automática y robusta
  filtrarPorCategoriaP(subcategoria: string) {
    const sub = subcategoria.trim().toLowerCase();

    this.productosFiltrados = this.productos.filter(producto => {
      return (
        (producto.nombre && producto.nombre.toLowerCase().includes(sub)) ||
        (producto.descripcion && producto.descripcion.toLowerCase().includes(sub)) ||
        (producto.categoria && producto.categoria.toLowerCase().includes(sub)) ||
        (producto.codigo && producto.codigo.toLowerCase().includes(sub))
      );
    });

    this.cdr.detectChanges();
    setTimeout(() => {
      const cards = document.querySelectorAll('.producto-card');
      cards.forEach((card) => card.classList.add('visible'));
    }, 100);
  }


  resetFiltrado() {
    // Si hay un término de búsqueda activo, límpialo
    this.searchTerm = '';
    // Restaura todos los productos
    this.productosFiltrados = [...this.productos];
    this.cdr.detectChanges();
    setTimeout(() => {
      const cards = document.querySelectorAll('.producto-card');
      cards.forEach((card) => card.classList.add('visible'));
    }, 100);
  }

  ngAfterViewInit() {
    setTimeout(() => {
      const cards = document.querySelectorAll('.producto-card');
      cards.forEach((card) => card.classList.add('visible'));
    }, 100);
  }

  openMenu() {
    this.isMenuOpen = true;
  }

  closeMenu() {
    this.isMenuOpen = false;
  }

  onBuscarProductos(event: any) {
    const value = (event.target.value || '').trim().toLowerCase();
    this.searchTerm = value;

    if (!value) {
      this.resetFiltrado();

      setTimeout(() => {
        const cards = document.querySelectorAll('.producto-card');
        cards.forEach((card) => card.classList.add('visible'));
      }, 100);

      return;
    }

    this.productosFiltrados = this.productos.filter(producto => {
      return (
        producto.nombre.toLowerCase().includes(value) ||
        producto.descripcion.toLowerCase().includes(value) ||
        producto.codigo.toLowerCase().includes(value)
      );
    });

    console.log('Filtrados:', this.productosFiltrados);

    this.cdr.detectChanges();

    setTimeout(() => {
      const cards = document.querySelectorAll('.producto-card');
      cards.forEach((card) => card.classList.add('visible'));
    }, 100);
  }
  
}
